# 玩家出牌的最大等待时间（秒）
turn-timeout: 60
# 是否开启计分板的显示部分信息，禁用将用聊天消息代替，Folia核心强制使用聊天消息代替
scoreboard-enabled: true

# 金币赛设置，需要Vault经济支持
bounty-enabled: true  # 是否启用金币赛功能
money-multiplier: 50  # 金币倍率，最终金币=游戏倍数*这个值